### ISSUE TITLE
Read from Buffer?

### ISSUE THREAD

**Issue by tommedema** [marvinpeter95/fs-zip#1]
All API methods seem to require a file path, yet I already have my .zip file in memory. Can I pass in a Buffer instead?

**Comment by marvinpeter95** [comment]
No, this is not possible. fs-zip is a near drop-in replacement for the Node.js fs library. The reasoning behind creating it was to access file and zip file contents with the same API without the need to know whether the path is within a zip or not.

For your use case I would recommend JSZip, which is the library fs-zip builds upon.
https://stuk.github.io/jszip/documentation/howto/read_zip.html
